import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service · Sozialzynk',
  description: 'Terms and conditions for using the Sozialzynk platform.',
};

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using Sozialzynk (the "Service"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree to these Terms, do not use the Service.

These Terms constitute a legally binding agreement between you and Sozialzynk. We reserve the right to update these Terms at any time. We will notify you of material changes by email and in-app notice at least 14 days in advance. Continued use of the Service after the effective date of a change constitutes acceptance of the revised Terms.`,
  },
  {
    id: 'description',
    title: '2. Description of Service',
    content: `Sozialzynk is an AI-powered YouTube Content Operating System. The Service enables you to:

• Research trending topics, discover competitor gaps, and identify viral opportunities using AI research agents.
• Generate AI-assisted scripts, fact-checked against source material, with monetization and copyright compliance built in.
• Create AI characters, voice narrations, thumbnail images, and short-form video content.
• Publish, schedule, and manage content on YouTube and secondary platforms through a human-in-the-loop approval workflow.
• Analyze channel performance and run A/B tests on titles and thumbnails.
• Manage your content pipeline via an AI Copilot with voice and text interaction.

Every piece of content generated by the AI pipeline passes through the Compliance Intelligence Engine before it is made available for publishing. The Service is provided on a subscription basis. Features available to you depend on your subscription plan (Free or Pro).`,
  },
  {
    id: 'accounts',
    title: '3. User Accounts',
    content: `To access most features of the Service, you must create an account. You agree to:

• Provide accurate, current, and complete information during registration.
• Maintain the security of your password, passkey, or other authentication credential and accept responsibility for all activity that occurs under your account.
• Notify us immediately at security@sozialzync.com if you suspect unauthorized access to your account.
• Not share your account credentials with any third party.

You are responsible for all content published through your account, whether generated by you or by our AI tools. We reserve the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    id: 'acceptable-use',
    title: '4. Acceptable Use',
    content: `You agree to use the Service only for lawful purposes and in compliance with all applicable laws. You must not use the Service to:

• Create, distribute, or publish spam, misinformation, or deceptive content.
• Infringe the intellectual property rights of any person or entity.
• Impersonate any individual, organization, or brand.
• Publish content that is defamatory, harassing, abusive, obscene, or otherwise objectionable.
• Violate the terms of service or community guidelines of YouTube or any other connected platform.
• Circumvent platform monetization policies, including YouTube's Partner Program policies.
• Publish AI-generated content that you know to be factually false or intended to mislead viewers.
• Reverse engineer, decompile, or attempt to extract the source code of the Service.
• Use automated means (bots, scrapers) to access the Service beyond our official API.
• Engage in any activity that disrupts or impairs the integrity or performance of the Service.`,
  },
  {
    id: 'content-ownership',
    title: '5. Content Ownership',
    content: `Your Content: You retain full ownership of the content you create using the Service, including AI-assisted outputs that you edit and publish. By using the Service, you grant Sozialzynk a limited, non-exclusive, royalty-free license to store, process, and transmit your content solely for the purpose of delivering the Service to you.

Our Content: The Service itself, including its design, code, AI agent pipeline, and proprietary algorithms, is owned by Sozialzynk and protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works from the Service or its components without our written consent.

AI-Generated Content: You acknowledge that AI outputs — including scripts, characters, voice narrations, thumbnails, and images — may be similar to content generated for other users. Sozialzynk does not warrant that AI-generated content is unique or free from similarity to third-party works. You are responsible for reviewing all AI output before publishing.`,
  },
  {
    id: 'ai-content',
    title: '6. AI-Generated Content & Agent Pipeline',
    content: `The Service uses a multi-agent AI pipeline to generate content including scripts, images, characters, voice narrations, audio tracks, and short-form video. You acknowledge and agree that:

• All factual claims in generated scripts are verified by our FactCheckAgent against sources gathered by ResearchAgent. However, you remain solely responsible for reviewing and verifying AI output before publishing.
• Sozialzynk does not guarantee the accuracy, completeness, or fitness for purpose of AI-generated content.
• You must not publish AI-generated content that you know to be false or misleading.
• Every piece of content must pass the Compliance Intelligence Engine before it is made available for publishing. You must not use or implement any code path that bypasses this compliance gate.
• Compliance tools are designed to help identify potential issues but do not constitute a guarantee that content will be monetized or approved by YouTube or any other platform.
• AI-generated voice narrations, characters, and music use licensed AI providers. Provenance metadata is stored with every generated asset. You agree not to remove or alter this metadata.
• Human approval is required before content is published to YouTube, unless you have explicitly enabled scheduled auto-publish and the item has already passed compliance.`,
  },
  {
    id: 'ad-revenue-programme',
    title: '7. Ad Revenue Programme',
    content: `The Ad Revenue Programme is available to creators on the Pro plan. By enabling ad revenue on a project, you agree that:

• SozialZynk will display your content on the public Browse page and count impressions.
• Credits are distributed at a rate of 50 credits per 1,000 verified Browse page views, paid daily to your bonus credit wallet.
• Credits are non-transferable and have no cash value outside the SozialZynk platform. They may be used to purchase AI credits or other platform services.
• SozialZynk reserves the right to modify the CPM rate, minimum payout threshold, or discontinue the programme with 30 days' notice.
• Content must comply with all Acceptable Use and Compliance Engine requirements to remain eligible for the programme. Disabling ad revenue or removing a project from Browse immediately suspends credit accrual.
• SozialZynk does not guarantee any specific earnings from the Ad Revenue Programme.`,
  },
  {
    id: 'platform-integrations',
    title: '8. Platform Integrations',
    content: `When you connect your YouTube account or other social accounts to Sozialzynk, you:

• Grant Sozialzynk the OAuth permissions necessary to publish content and retrieve analytics on your behalf, using the YouTube Data API and other official APIs.
• Remain solely responsible for ensuring that your use of those platforms complies with each platform's own terms of service, community guidelines, and content policies — including YouTube's Terms of Service and Creator Policies.
• Acknowledge that platform APIs and policies may change at any time, which may affect the availability of certain features.
• Understand that Sozialzynk is not affiliated with, endorsed by, or sponsored by YouTube (Google LLC), Meta, TikTok, LinkedIn, or X Corp.

You can revoke platform access at any time from your Sozialzynk account settings or from the connected platform's security settings.`,
  },
  {
    id: 'billing',
    title: '9. Subscription and Billing',
    content: `Plans: SozialZynk offers Free and Pro subscription plans. Plan features and limits are described on our pricing page and may be updated from time to time with reasonable notice.

Free: $0 forever — 2,000 AI credits/month, unlimited channels connected, unlimited AI Copilot queries, unlimited Shorts Studio. Content may be published to the SozialZynk feed. Exports, downloads, and publishing to external platforms (YouTube, Instagram, etc.) are not available on the Free plan.

Pro: $17/month — unlimited AI credits, unlimited channels, full Creative Studio (all AI agents), publish to YouTube, Instagram, and all connected platforms, export and download files, A/B testing, analytics, ad revenue monetization, own branding (white-label), and dedicated SLA & support.

Organisation Features: Team seats, role management, shared organisation wallet, and custom AI model training are available exclusively to admin and super admin accounts. These features are not available for purchase as a separate plan tier.

Billing: Paid subscriptions are billed in advance on a monthly basis through Stripe. By subscribing, you authorize SozialZynk to charge your payment method on a recurring basis.

AI Credits: Certain AI operations (script generation, image generation, voice synthesis, character creation) consume AI credits. Credits included in your plan refresh monthly. Additional credits may be purchased from the Wallet section.

Cancellation: You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period. We do not provide refunds for partial billing periods except where required by law.

Price Changes: We will notify you at least 30 days before any price changes take effect. Continued use of the Service after the effective date constitutes acceptance of the new pricing.

Taxes: Prices may be exclusive of applicable taxes. You are responsible for all taxes applicable to your subscription in your jurisdiction.`,
  },
  {
    id: 'prohibited',
    title: '10. Prohibited Activities',
    content: `In addition to the Acceptable Use policy in Section 4, the following are expressly prohibited:

• Using the Service to generate content designed to manipulate search engines or YouTube's recommendation algorithm in a deceptive manner.
• Creating synthetic media (deepfakes) that misrepresents real individuals without their explicit consent.
• Using the AI Copilot or any agent to generate scripts that make unverified medical, legal, or financial claims intended to harm viewers.
• Using the Service to build a competing product or to benchmark the Service for publication without our written consent.
• Attempting to probe, scan, or test the vulnerability of the Service or circumvent any security measure, including the Compliance Intelligence Engine.
• Selling, reselling, or sublicensing access to the Service without our written authorization.

Violation of these prohibitions may result in immediate account suspension and potential legal action.`,
  },
  {
    id: 'disclaimers',
    title: '11. Disclaimers and Limitation of Liability',
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL COMPONENTS. WE ARE NOT RESPONSIBLE FOR THE ACTIONS OF THIRD-PARTY PLATFORMS (YOUTUBE, INSTAGRAM, TIKTOK, ETC.) OR CHANGES TO THEIR APIS OR POLICIES. WE ARE NOT RESPONSIBLE FOR YOUTUBE MONETIZATION DECISIONS OR CONTENT STRIKES RESULTING FROM CONTENT YOU CHOOSE TO PUBLISH.

TO THE FULLEST EXTENT PERMITTED BY LAW, Sozialzynk'S TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO Sozialzynk IN THE 12 MONTHS PRECEDING THE CLAIM. IN NO EVENT SHALL WE BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.`,
  },
  {
    id: 'termination',
    title: '12. Termination',
    content: `You may terminate your account at any time by deleting it from your account settings. Upon termination, your data will be deleted in accordance with our Privacy Policy (within 90 days).

We reserve the right to suspend or terminate your account immediately, without notice, if we reasonably believe you have violated these Terms, engaged in fraudulent activity, attempted to bypass the Compliance Intelligence Engine, or pose a risk to the Service or other users.

Upon termination, your right to use the Service ceases immediately. Provisions of these Terms that by their nature should survive termination (including ownership, disclaimers, and limitation of liability) shall remain in effect.`,
  },
  {
    id: 'governing-law',
    title: '13. Governing Law',
    content: `These Terms are governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions.

Any dispute arising out of or relating to these Terms or the Service shall be subject to the exclusive jurisdiction of the state and federal courts located in Delaware. You waive any objection to the laying of venue in such courts.

If you are a consumer in the European Union, you may also be entitled to the protections of the mandatory consumer protection laws in your country of residence.`,
  },
  {
    id: 'contact',
    title: '14. Contact',
    content: `If you have questions about these Terms or the Service, please contact us:

Legal inquiries: legal@sozialzync.com
General support: support@sozialzync.com
Privacy matters: privacy@sozialzync.com

We aim to respond to all inquiries within 5 business days.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div style={{ background: 'linear-gradient(135deg, #4f2ec4 0%, #374151 55%, #7c5ae8 100%)' }} className="py-16 px-4">
        <div className="max-w-3xl mx-auto">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-white/70 hover:text-white text-sm font-medium mb-8 transition-colors"
          >
            ← Back to Sozialzynk
          </Link>
          <div className="inline-flex items-center gap-2 bg-white/15 text-white/85 text-xs font-semibold px-3 py-1.5 rounded-full mb-4">
            Legal
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight mb-3">
            Terms of Service
          </h1>
          <p className="text-white/65 text-base">
            Effective date: <strong className="text-white/85">August 7, 2026</strong>
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Intro */}
        <div className="bg-white rounded-2xl p-6 mb-8 border border-gray-100 shadow-sm">
          <p className="text-gray-600 leading-relaxed">
            Please read these Terms of Service carefully before using Sozialzynk. These Terms govern your
            access to and use of our AI-powered YouTube Content Operating System. By using the Service, you agree
            to be bound by these Terms.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-6">
          {SECTIONS.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm"
            >
              <h2 className="text-lg font-bold text-gray-900 pb-3 mb-4 border-b border-gray-100">
                {section.title}
              </h2>
              <div className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">
                {section.content}
              </div>
            </section>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-10 text-center text-sm text-gray-400 space-y-2">
          <p>Last updated: August 7, 2026</p>
          <p>
            Also read our{' '}
            <Link href="/privacy" className="text-[#374151] hover:underline font-medium">
              Privacy Policy
            </Link>
          </p>
          <p>
            <Link href="/" className="text-[#374151] hover:underline">
              ← Return to Sozialzynk
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
