import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Sozialzynk — AI Content Creator Platform',
    short_name: 'Sozialzynk',
    description: 'AI-powered content creator platform. Research, script, create and publish across all your channels — from one intelligent workspace.',
    start_url: '/browse',
    scope: '/',
    display: 'standalone',
    display_override: ['window-controls-overlay', 'standalone', 'minimal-ui'],
    background_color: '#111827',
    theme_color: '#374151',
    orientation: 'portrait-primary',
    lang: 'en',
    dir: 'ltr',
    categories: ['productivity', 'entertainment', 'social'],
    icons: [
      // PNG icons generated by icon.tsx via Next.js ImageResponse —
      // dark background + white/gray Zk logo, proper safe-zone padding.
      {
        src: '/icon',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
      // SVG fallback for browsers that support it
      {
        src: '/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any',
      },
    ],
    shortcuts: [
      {
        name: 'AI Copilot',
        url: '/copilot',
        description: 'Open the AI Copilot',
      },
      {
        name: 'New Project',
        url: '/projects',
        description: 'Start a new content project',
      },
      {
        name: 'Shorts Studio',
        url: '/shorts-studio',
        description: 'Create YouTube Shorts',
      },
    ],
    // @reason: Next.js MetadataRoute.Manifest['screenshots'] element type doesn't expose an index signature
    // Cast the whole array so we can include the standard W3C `form_factor` and `label` fields.
    screenshots: ([
      { src: '/screenshots/home.png',        sizes: '1280x800', type: 'image/png', form_factor: 'wide',   label: 'Sozialzynk dashboard — AI Content Creator Platform' },
      { src: '/screenshots/copilot.png',     sizes: '1280x800', type: 'image/png', form_factor: 'wide',   label: 'AI Copilot — create content by conversation' },
      { src: '/screenshots/home-mobile.png', sizes: '390x844',  type: 'image/png', form_factor: 'narrow', label: 'Mobile dashboard' },
    ] as unknown) as MetadataRoute.Manifest['screenshots'],
  };
}
