import type { IPlugin, PluginContext, PluginHook } from '../plugin.types';

const DISCLOSURE_PHRASES = ['ai generated', 'made with ai', 'created with ai', 'sponsored', 'paid partnership', '#ad', '#sponsored'];
const AI_CONTENT_SIGNALS = ['ai-generated', 'generated by ai', 'sozialzync'];

export const DisclosureGuardPlugin: IPlugin = {
  id: 'builtin:disclosure-guard',
  name: 'Disclosure Guard',
  version: '1.0.0',
  hooks: ['before:publish'],
  async execute(hook: PluginHook, ctx: PluginContext): Promise<PluginContext> {
    if (hook !== 'before:publish') return ctx;
    const description = ((ctx.data['description'] as string | undefined) ?? '').toLowerCase();
    const tags = ((ctx.data['tags'] as string[] | undefined) ?? []).map(t => t.toLowerCase());
    const warnings: string[] = [];
    const hasAiSignal = AI_CONTENT_SIGNALS.some(s => description.includes(s) || tags.some(t => t.includes(s)));
    const hasDisclosure = DISCLOSURE_PHRASES.some(p => description.includes(p));
    if (hasAiSignal && !hasDisclosure) {
      warnings.push('Content may be AI-generated but lacks a disclosure statement. Consider adding "AI-assisted content" to the description.');
    }
    return { ...ctx, data: { ...ctx.data, disclosureWarnings: warnings } };
  },
};
